# Generated by Django 6.0.4 on 2026-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='board_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
