# Generated by Django 6.0.4 on 2026-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_board_reference_question_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
