# Generated by Django 6.0.4 on 2026-06-01 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_chapter_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_special_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BoardPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_free', models.BooleanField(default=False)),
                ('is_special_locked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_papers', to='exams.subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exams.boardpaper'),
        ),
    ]
