# Generated by Django 6.0.4 on 2026-06-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_question_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
