# Generated by Django 6.0.4 on 2026-06-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardpaper',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id']},
        ),
    ]
