# Generated by Django 6.0.4 on 2026-06-09 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_group_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='sender_number',
            field=models.CharField(blank=True, help_text='The number user sent money from', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SSC Premium Access', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Original Price', max_digits=8)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Offer Price (Keep blank if no discount)', max_digits=8, null=True)),
                ('features', models.JSONField(default=list, help_text='Enter features as a JSON list. e.g., ["Access to all SSC chapters", "Unlimited MCQ"]')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this plan from the frontend')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='exams.level')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='users.subscriptionplan'),
        ),
    ]
