# Generated by Django 6.0.4 on 2026-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_sender_number_alter_subscription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Course expiry date (e.g., Dec 31, 2028)', null=True),
        ),
    ]
