# Generated by Django 6.0.4 on 2026-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptionplan_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=730, help_text='Course validity in days (e.g., 365 for 1 year, 730 for 2 years)'),
        ),
    ]
