# Generated by Django 6.0.4 on 2026-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscriptionplan_valid_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(default='017XX-XXXXXX', help_text='Number to show for payment', max_length=15)),
                ('page_title', models.CharField(default='Unlock your full potential.', max_length=255)),
                ('page_subtitle', models.TextField(default='Join thousands of students and get unlimited access.')),
                ('benefits', models.JSONField(default=list, help_text='Enter benefits as JSON list. e.g. ["Benefit 1", "Benefit 2"]')),
            ],
            options={
                'verbose_name': 'Checkout Page Setting',
                'verbose_name_plural': 'Checkout Page Settings',
            },
        ),
    ]
