# Generated by Django 6.0.4 on 2026-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_checkoutsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Course expiry date', null=True),
        ),
    ]
