# Generated by Django 6.0.4 on 2026-06-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_subscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiry_date',
        ),
    ]
