# Generated by Django 6.0.4 on 2026-06-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_subscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
